version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "digitalcorehub"
    assignees:
      - "digitalcorehub"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "illuminate/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "digitalcorehub"
    assignees:
      - "digitalcorehub"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
