<?php

declare(strict_types=1);

namespace DigitalCoreHub\LaravelApiDocx\Services;

/**
 * Generates a modern ReDoc HTML page for API documentation.
 */
class ReDocGenerator
{
    /**
     * Generate a complete HTML page with ReDoc integration.
     */
    public function generate(string $openApiJson): string
    {
        $html = $this->getHtmlTemplate();
        $openApiJson = htmlspecialchars($openApiJson, ENT_QUOTES, 'UTF-8');

        return str_replace('{{OPENAPI_JSON}}', $openApiJson, $html);
    }

    /**
     * Get the HTML template with modern styling.
     */
    private function getHtmlTemplate(): string
    {
        return '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        
        .header {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            padding: 1rem 2rem;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
            position: sticky;
            top: 0;
            z-index: 1000;
        }
        
        .header h1 {
            color: #2d3748;
            font-size: 1.875rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }
        
        .header p {
            color: #718096;
            font-size: 1rem;
            font-weight: 400;
        }
        
        .badge {
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-left: 1rem;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }
        
        .redoc-container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            margin-top: 2rem;
        }
        
        .loading {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 400px;
            color: #718096;
            font-size: 1.125rem;
        }
        
        .spinner {
            width: 24px;
            height: 24px;
            border: 3px solid #e2e8f0;
            border-top: 3px solid #667eea;
            border-radius: 50%;
            animation: spin 1s linear infinite;
            margin-right: 0.75rem;
        }
        
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        
        .footer {
            text-align: center;
            padding: 2rem;
            color: rgba(255, 255, 255, 0.8);
            font-size: 0.875rem;
        }
        
        .footer a {
            color: white;
            text-decoration: none;
            font-weight: 500;
        }
        
        .footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>API Documentation <span class="badge">Laravel API Docx</span></h1>
        <p>Interactive API documentation generated automatically</p>
    </div>
    
    <div class="container">
        <div class="redoc-container">
            <div id="redoc-container">
                <div class="loading">
                    <div class="spinner"></div>
                    Loading documentation...
                </div>
            </div>
        </div>
    </div>
    
    <div class="footer">
        <p>Generated by <a href="https://github.com/digitalcorehub/laravel-api-docx" target="_blank">Laravel API Docx</a> • Made with ❤️ by <a href="https://digitalcorehub.com" target="_blank">Digital Core Hub</a></p>
    </div>

    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
    <script>
        const openApiSpec = {{OPENAPI_JSON}};
        
        Redoc.init(openApiSpec, {
            theme: {
                colors: {
                    primary: {
                        main: "#667eea"
                    }
                },
                typography: {
                    fontSize: "14px",
                    lineHeight: "1.5em",
                    code: {
                        fontSize: "13px",
                        fontFamily: "JetBrains Mono, Consolas, Monaco, monospace"
                    },
                    headings: {
                        fontFamily: "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif",
                        fontWeight: "600"
                    }
                },
                spacing: {
                    unit: 5,
                    sectionHorizontal: 40,
                    sectionVertical: 40
                },
                breakpoints: {
                    medium: "50rem",
                    large: "85rem",
                    xlarge: "120rem"
                }
            },
            scrollYOffset: 60,
            hideDownloadButton: false,
            hideHostname: false,
            hideLoading: true,
            nativeScrollbars: false,
            pathInMiddlePanel: true,
            requiredPropsFirst: true,
            sortPropsAlphabetically: false,
            showObjectSchemaExamples: true,
            menuToggle: true,
            jsonSampleExpandLevel: 2,
            hideSingleRequestSampleTab: false,
            expandSingleSchemaField: false,
            schemaExpansionLevel: 2,
            showExtensions: false,
            hideSchemaPattern: false,
            expandDefaultServerVariables: true,
            maxDisplayedEnumValues: 10,
            hideDownloadButton: false,
            downloadFileName: "api-documentation",
            downloadDefinitionUrl: window.location.href.replace(".html", ".json")
        }, document.getElementById("redoc-container"));
    </script>
</body>
</html>';
    }
}
